name: Deploy Project
on:
  pull_request:
    types: [opened,edited]
  workflow_dispatch:
  push:
    branches:
      - main
      - 'dev-*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependecnies
        run: npm ci
      - name: Run Tests
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependecnies
        run: npm ci
      - name: Run Tests
        run: npm test
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."